name = "tallyho-web"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[[analytics_engine_datasets]]
  binding = "TALLYHO"
  dataset = "metricsDataset"